### ISSUE TITLE
Use of missing aggregations

### ISSUE THREAD

**Issue by janatacke** [quarkiverse/quarkus-opensearch#350]
I want to do a composite aggregation and include a nullcheck. I have seen that there is .missing. However, I get no results back as soon as I add it. Without .missing my query works. Can someone tell me how to use missing correctly? Here is my query:

`	public static Map<String, CompositeAggregationSource> buildTermsAggregation(String name, String field) {
		return Map.of(name, new CompositeAggregationSource.Builder().terms(t -> 
                  t.field(field).missing(FieldValue.of("missing"))).build());
	}`

**Comment by sboeckelmann** [comment]
Thank you for reaching out!

This issue appears to be more related to the OpenSearch functionality itself rather than the Quarkus OpenSearch extension. Specifically, it concerns the use of the .missing parameter in composite aggregations, which is a feature of OpenSearch.

I recommend posting this question on the [OpenSearch GitHub repository](https://github.com/opensearch-project/OpenSearch) or discussing it on the OpenSearch community forums, where the maintainers and contributors for OpenSearch can provide more accurate guidance.

Therefore, I will be closing this issue here. Please feel free to reach out if you have any concerns directly related to the Quarkus OpenSearch extension. 😊
