### ISSUE TITLE
Examples of usage

### ISSUE THREAD

**Issue by AbdallahAhmed** [quarkiverse/quarkus-opensearch#61]
Would you add some examples of how to use the extension and to  make basic search and multi-index search

**Comment by sboeckelmann** [comment]
A very basic documentation on how to add to your project already exists:
https://github.com/quarkiverse/quarkus-opensearch/blob/main/docs/modules/ROOT/pages/index.adoc

Maybe I will add a few examples on OpenSearch client injection and a few simple examples some time in the future.

For now you can take a look at the integration tests:
https://github.com/quarkiverse/quarkus-opensearch/blob/main/opensearch-java-client/deployment/src/test/java/io/quarkiverse/opensearch/client/deployment/test/OpenSearchClientTest.java

https://github.com/quarkiverse/quarkus-opensearch/blob/main/opensearch-rest-high-level-client/deployment/src/test/java/io/quarkiverse/opensearch/restclient/highlevel/deployment/test/OpenSearchRestHighLevelClientInjectionTest.java

https://github.com/quarkiverse/quarkus-opensearch/blob/main/opensearch-rest-client/deployment/src/test/java/io/quarkiverse/opensearch/restclient/lowlevel/deployment/test/TestResource.java

But for basic search and multi-index search, please refer to the official OpenSearch documentation.
https://opensearch.org/docs/latest/clients/java/

It's been some time since you created this issue, so hopefully you already succeeded in figuring things out. Maybe you even would like to share your experience with others. If that's the case, a pull request containing improvements for the current documentation is always greatly appreciated.

**Comment by sboeckelmann** [comment]
duplicates https://github.com/quarkiverse/quarkus-opensearch/issues/8
